package tui

import (
	_ "embed"
	"strings"
)

// logo.go renders the startup banner: a colored ASCII-art logo (generated by
// oh-my-logo) shown in the chat pane when the program boots. The logo is
// embedded into the binary at build time (logo.txt in this directory), so the
// banner works without the file present at runtime. It is display only: it is
// never persisted into sessions, and it does not reappear for /new, Ctrl+N, or
// session switches - only a fresh program start shows it.

//go:embed logo.txt
var logoFileContent string

// startupLogoLines holds the cleaned logo lines (ANSI colors preserved,
// terminal-control artifacts removed), derived from the embedded logo file at
// package init. Empty when the embedded content carries no visible art.
var startupLogoLines = cleanLogoContent(logoFileContent)

// startupTagline is rendered underneath the logo in the startup banner. A var
// so it can be customized (e.g. wired to config) without touching the loader.
var startupTagline = "High-autonomy AI research & navigation agent"

// cleanLogoContent cleans raw logo file content into the visible rows with
// their truecolor ANSI sequences intact. It returns nil when the content
// carries no visible art so the startup banner degrades silently. The cleanup:
//   - trims leading/trailing blank lines
//   - drops leading/trailing lines that carry only escape artifacts (the
//     reset / cursor-show / erase-line sequences oh-my-logo appends)
//   - strips those terminal-control sequences from every line while keeping
//     the truecolor foreground sequences (ESC[38;2;R;G;Bm) and the
//     default-color reset (ESC[39m) that color the logo glyphs
func cleanLogoContent(content string) []string {
	raw := strings.Split(strings.TrimRight(content, "\n"), "\n")

	// Trim leading/trailing blank lines.
	start, end := 0, len(raw)
	for start < end && strings.TrimSpace(raw[start]) == "" {
		start++
	}
	for end > start && strings.TrimSpace(raw[end-1]) == "" {
		end--
	}
	// Trim leading/trailing lines that carry only terminal-control artifacts.
	for start < end && !hasVisibleRune(raw[start]) {
		start++
	}
	for end > start && !hasVisibleRune(raw[end-1]) {
		end--
	}
	if start >= end {
		return nil
	}

	lines := make([]string, 0, end-start)
	for _, line := range raw[start:end] {
		lines = append(lines, stripTerminalControl(line))
	}
	return lines
}

// stripTerminalControl removes CSI sequences that are not part of the logo's
// coloring (cursor show/hide, erase-line, reset) so they cannot interfere with
// the TUI's own terminal state when the banner renders.
func stripTerminalControl(line string) string {
	var b strings.Builder
	b.Grow(len(line))
	for i := 0; i < len(line); {
		if line[i] == 0x1b && i+1 < len(line) && line[i+1] == '[' {
			// Find the final byte of the CSI sequence (0x40-0x7e).
			j := i + 2
			for j < len(line) && !(line[j] >= 0x40 && line[j] <= 0x7e) {
				j++
			}
			if j < len(line) {
				seq := line[i : j+1]
				if isLogoColor(seq) {
					b.WriteString(seq)
				}
				i = j + 1
			} else {
				i = len(line)
			}
			continue
		}
		b.WriteByte(line[i])
		i++
	}
	return b.String()
}

// isLogoColor reports whether a CSI sequence is one of the sequences used to
// color the logo: truecolor foreground (ESC[38;2;R;G;Bm) or default foreground
// (ESC[39m). Anything else is treated as a generator artifact and stripped.
func isLogoColor(seq string) bool {
	return strings.HasPrefix(seq, "\x1b[38;2;") || seq == "\x1b[39m"
}

// hasVisibleRune reports whether the line contains any printable byte outside
// of ANSI escape sequences. Used to distinguish logo rows from trailing
// terminal-control artifacts.
func hasVisibleRune(line string) bool {
	for i := 0; i < len(line); i++ {
		if line[i] == 0x1b && i+1 < len(line) && line[i+1] == '[' {
			// Skip the whole CSI sequence.
			j := i + 2
			for j < len(line) && !(line[j] >= 0x40 && line[j] <= 0x7e) {
				j++
			}
			if j < len(line) {
				i = j
			} else {
				i = len(line)
			}
			continue
		}
		if line[i] > 0x20 && line[i] != 0x7f {
			return true
		}
	}
	return false
}
